### PR TITLE
Add timeout support

### PR DESCRIPTION
**Pull request by osantana**

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks!

I wonder if we should make a non-zero default like 15 seconds to prevent awful edge cases.

**Comment by osantana** [comment]
I put 0 to keep backward compatibility (I think that some users are not prepared to handle Timeout exceptions and this error will break their code... but I'm ok to change it to a big number...)

**Comment by JoshData** [comment]
Ah, right. Well, better then would be for us to catch the timeout and raise one of the library's exceptions to signal that the email address was not resolvable.

**Comment by JoshData** [comment]
What's a good way to test that the timeout is working? Is there an email address you're using that times out?

**Comment by osantana** [comment]
> What's a good way to test that the timeout is working? Is there an email address you're using that times out?

I think the only way to test it is monkeypatching `socket` module to force it to rise a Timeout error... I never did this before but I can try...

**Comment by JoshData** [comment]
OK in that case I'll merge. :)

**Pull request merged**
