### PR TITLE
Change: Default dns resolve, fallback dns query

### LINKED ISSUE #45: Deprecation warning under Python 3.8
During my tests I'm seeing this:

```python
.../lib/python3.8/site-packages/email_validator/__init__.py:458: DeprecationWarning: please use dns.resolver.resolve() instead
    response = dns.resolver.query(domain, "MX")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

I'm working with email-validator version 1.1.1 from PyPI

### PR DESCRIPTION
**Pull request by 0xdade**
Closes #45 by defaulting to resolver.resolve and only falling back to resolver.query when resolver.resolve isn't present.

Due to the limited scope where dns resolver is used, this seemed like a cleaner solution than assigning a `resolve` function to the foreign resolver object.

Unfortunately the test suite catastrophically fails in python 2.7.18 so the only tests I'm able to provide are the following manual tests. The string `Falling back to query` was added for the sake of illustration and is not included in the patch.

### Python 3.8.4

```python
➜ python 
Python 3.8.4 (default, Jul 14 2020, 22:50:28) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import email_validator
>>> email_validator.validate_email("dade@actualcrimes.org")
<ValidatedEmail dade@actualcrimes.org>
>>> email_validator.validate_email("dade@actuallimes.org")
Traceback (most recent call last):
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 466, in validate_email_deliverability
    response = resolve_shim(resolver, domain, "MX")
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 446, in resolve_shim
    return resolver.resolve(domain, record)
  File "/home/dade/python-email-validator/venv/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/dade/python-email-validator/venv/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: actuallimes.org.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 473, in validate_email_deliverability
    response = resolve_shim(resolver, domain, "A")
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 446, in resolve_shim
    return resolver.resolve(domain, record)
  File "/home/dade/python-email-validator/venv/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/dade/python-email-validator/venv/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: actuallimes.org.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 480, in validate_email_deliverability
    response = resolve_shim(resolver, domain, "AAAA")
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 446, in resolve_shim
    return resolver.resolve(domain, record)
  File "/home/dade/python-email-validator/venv/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/dade/python-email-validator/venv/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: actuallimes.org.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 265, in validate_email
    deliverability_info = validate_email_deliverability(ret["domain"], ret["domain_i18n"], timeout)
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 487, in validate_email_deliverability
    raise EmailUndeliverableError("The domain name %s does not exist." % domain_i18n)
email_validator.EmailUndeliverableError: The domain name actuallimes.org does not exist.
```

### Python 2.7.18

```python
➜ python
Python 2.7.18 (default, Aug  2 2020, 00:11:02) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import email_validator
>>> email_validator.validate_email("dade@actualcrimes.org")
Falling back to query
<ValidatedEmail dade@actualcrimes.org>
>>> email_validator.validate_email("dade@actuallimes.org")
Falling back to query
Falling back to query
Falling back to query
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "email_validator/__init__.py", line 265, in validate_email
    deliverability_info = validate_email_deliverability(ret["domain"], ret["domain_i18n"], timeout)
  File "email_validator/__init__.py", line 487, in validate_email_deliverability
    raise EmailUndeliverableError("The domain name %s does not exist." % domain_i18n)
email_validator.EmailUndeliverableError: The domain name actuallimes.org does not exist.
```

### CODE REVIEW

**Comment by JoshData** [comment]
Excellent. I made a few changes:

* Renamed the shim method for clarity.
* The `+ "."` change to the domain (#30) seems like it can be dropped if we use `resolve`.
* Added some code comments.

Would you mind retesting?

**Comment by 0xdade** [comment]
Looks like everything functionally checks out.

## Python 2.7.18
```
python-email-validator on  resolve_shim via 🐍 2.7.18 
➜ python                          
Python 2.7.18 (default, Aug  2 2020, 00:11:02) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import email_validator
>>> email_validator.validate_email("dade@actualcrimes.org")
<ValidatedEmail dade@actualcrimes.org>
>>> email_validator.validate_email("dade@actuallimes.org")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "email_validator/__init__.py", line 265, in validate_email
    deliverability_info = validate_email_deliverability(ret["domain"], ret["domain_i18n"], timeout)
  File "email_validator/__init__.py", line 491, in validate_email_deliverability
    raise EmailUndeliverableError("The domain name %s does not exist." % domain_i18n)
email_validator.EmailUndeliverableError: The domain name actuallimes.org does not exist.
```


## Python 3.8.4

```
python-email-validator on  resolve_shim via 🐍 2.7.18 took 1m 57s 
➜ pyenv local 3.8.4 

python-email-validator on  resolve_shim via 🐍 3.8.4 
➜ pipenv run pip install -e .
Creating a virtualenv for this project…
Pipfile: /home/dade/python-email-validator/Pipfile
Using /home/dade/.pyenv/versions/3.8.4/bin/python3.8 (3.8.4) to create virtualenv…
⠴ Creating virtual environment...created virtual environment CPython3.8.4.final.0-64 in 323ms
  creator CPython3Posix(dest=/home/dade/python-email-validator/.venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmptrn2d9s0)
    added seed packages: pip==20.1.1, setuptools==49.1.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/dade/python-email-validator/.venv
Creating a Pipfile for this project…
Obtaining file:///home/dade/python-email-validator
Collecting idna>=2.0.0
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.0.0-py3-none-any.whl (208 kB)
Installing collected packages: idna, dnspython, email-validator
  Running setup.py develop for email-validator
Successfully installed dnspython-2.0.0 email-validator idna-2.10

python-email-validator on  resolve_shim [?] via 🐍 3.8.4 took 6s 
➜ pipenv run python          
Python 3.8.4 (default, Jul 14 2020, 22:50:28) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import email_validator
>>> email_validator.validate_email("dade@actualcrimes.org")
<ValidatedEmail dade@actualcrimes.org>
>>> email_validator.validate_email("dade@actuallimes.org")
Traceback (most recent call last):
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 470, in validate_email_deliverability
    response = dns_resolver_resolve_shim(resolver, domain, "MX")
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 445, in dns_resolver_resolve_shim
    return resolver.resolve(domain, record)
  File "/home/dade/python-email-validator/.venv/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/dade/python-email-validator/.venv/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: actuallimes.org.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 477, in validate_email_deliverability
    response = dns_resolver_resolve_shim(resolver, domain, "A")
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 445, in dns_resolver_resolve_shim
    return resolver.resolve(domain, record)
  File "/home/dade/python-email-validator/.venv/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/dade/python-email-validator/.venv/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: actuallimes.org.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 484, in validate_email_deliverability
    response = dns_resolver_resolve_shim(resolver, domain, "AAAA")
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 445, in dns_resolver_resolve_shim
    return resolver.resolve(domain, record)
  File "/home/dade/python-email-validator/.venv/lib/python3.8/site-packages/dns/resolver.py", line 1030, in resolve
    (request, answer) = resolution.next_request()
  File "/home/dade/python-email-validator/.venv/lib/python3.8/site-packages/dns/resolver.py", line 584, in next_request
    raise NXDOMAIN(qnames=self.qnames_to_try,
dns.resolver.NXDOMAIN: The DNS query name does not exist: actuallimes.org.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 265, in validate_email
    deliverability_info = validate_email_deliverability(ret["domain"], ret["domain_i18n"], timeout)
  File "/home/dade/python-email-validator/email_validator/__init__.py", line 491, in validate_email_deliverability
    raise EmailUndeliverableError("The domain name %s does not exist." % domain_i18n)
email_validator.EmailUndeliverableError: The domain name actuallimes.org does not exist.
```

## Test Results

```
python-email-validator on  resolve_shim [?] via 🐍 3.8.4 
➜ pipenv run make test
pytest --cov=email_validator
==================================================== test session starts ====================================================
platform linux -- Python 3.8.4, pytest-5.2.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/dade/python-email-validator, inifile: setup.cfg, testpaths: tests
plugins: cov-2.8.1
collected 47 items                                                                                                          

tests/test_main.py ...............................................                                                    [100%]

----------- coverage: platform linux, python 3.8.4-final-0 -----------
Name                          Stmts   Miss  Cover
-------------------------------------------------
email_validator/__init__.py     219     67    69%


==================================================== 47 passed in 0.29s =====================================================
```

**Comment by JoshData** [comment]
Thanks, merging!

**Comment by ThiefMaster** [comment]
Just wondering, should the new call include `search=True` to mimic the old behavior?

**Comment by JoshData** [comment]
This actually matches the old behavior. Search was disabled by `domain += '.'` above the query.

**Pull request merged**
